# Generated by Django 4.2.2 on 2023-06-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_creacion_de_tablas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='sinopsos',
            new_name='sinopsis',
        ),
        migrations.AddField(
            model_name='categoria',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
