# Generated by Django 4.2.2 on 2023-06-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_agregue_columna_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='isStaff',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
