# Generated by Django 4.2.2 on 2023-06-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_agregue_columna_is_staff1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name_plural': 'imagenes'},
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.ImageField(upload_to=''),
        ),
    ]
