"""cree tabla mascotas

Revision ID: 36670ace7caa
Revises: d4f09bb199d5
Create Date: 2023-05-25 23:11:10.194168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36670ace7caa'
down_revision = 'd4f09bb199d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('apellido', sa.Text(), nullable=True),
    sa.Column('sexo', sa.Enum('Macho', 'Hembra', 'Otros', name='sexoenum'), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('raza', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascotas')
    # ### end Alembic commands ###
